import Head from 'next/head'
import Layout from "../components/Layout";
import {Container, Divider, Grid} from "@mantine/core";
import CardsCarousel from "../components/CardsCarousel";
import LatestTech from "../components/LatestTech";
import {JobCard} from "../components/JobCard";

export default function Home() {
    return (
        <>
            <Head>
                <title>Career Readiness Portal</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Layout>
                <Container p={"md"}>
                    <CardsCarousel/>
                </Container>
                <Divider m={"lg"}/>
                <LatestTech/>
                <Divider m={"lg"}/>
                <Container>
                    <Grid m={"md"} gutter={"md"}>
                        <Grid.Col lg={4}>
                            <JobCard location={"remote"}
                                     description={"Lorem ipsum dolor lorem ipsum dolor Lorem ipsum dolor lorem ipsum dolor Lorem ipsum dolor lorem ipsum dolor Lorem ipsum dolor lorem ipsum dolor"}
                                     title={"SDE Intern"}/>
                        </Grid.Col>
                        <Grid.Col lg={4}>
                            <JobCard location={"remote"}
                                     description={"Lorem ipsum dolor lorem ipsum dolor Lorem ipsum dolor lorem ipsum dolor Lorem ipsum dolor lorem ipsum dolor Lorem ipsum dolor lorem ipsum dolor"}
                                     title={"SDE Intern"}/>
                        </Grid.Col>
                        <Grid.Col lg={4}>
                            <JobCard location={"remote"}
                                     description={"Lorem ipsum dolor lorem ipsum dolor Lorem ipsum dolor lorem ipsum dolor Lorem ipsum dolor lorem ipsum dolor Lorem ipsum dolor lorem ipsum dolor"}
                                     title={"SDE Intern"}/>
                        </Grid.Col>
                    </Grid>
                </Container>
            </Layout>

        </>
    )
}
