import Head from 'next/head'
import Layout from "../components/Layout";
import {Container, Divider} from "@mantine/core";
import CardsCarousel from "../components/CardsCarousel";
import LatestTech from "../components/LatestTech";

export default function Home() {
    return (
        <>
            <Head>
                <title>Career Readiness Portal</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Layout>
                <Container p={"md"}>
                    <CardsCarousel/>
                </Container>
                <Divider m={"lg"}/>
                <LatestTech/>
                <Divider m={"lg"}/>
            </Layout>

        </>
    )
}
