import Head from 'next/head'
import Layout from "../components/Layout";
import {Container} from "@mantine/core";
import CardsCarousel from "../components/CardsCarousel";

export default function Home() {
    return (
        <>
            <Head>
                <title>Internship Portal</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Layout>
                <Container p={"md"}>
                    <CardsCarousel />
                </Container>
            </Layout>

        </>
    )
}
